### ISSUE TITLE
fails to connect to brltty

### ISSUE THREAD

**Issue by sthibaul** [brailcom/speechd-el#2]
As reported on https://lists.gnu.org/archive/html/speechd-discuss/2019-11/msg00000.html
there is an issue with connecting to brltty:

```
brltty-connection-error: (error Error in communication with BRLTTY:
(wrong-number-of-arguments #<subr encode-coding-string> 1))
```

**Comment by mz-pdm** [comment]
Fixed in speechd-el 2.9.
