### ISSUE TITLE
Provide a starter init.el file

### ISSUE THREAD

**Issue by pawelurbanski** [brailcom/speechd-el#4]
I started configuring Emacs under WSL2 Windows Subsystem for Linux. I got the sound working and the speechd-el package installed.

There are some issues I cannot find solutions for:

* Examples or a working init.el file, which can be very useful for beginners,
* Speechd-el does not honor speech-dispatcher settings set in the user configuration speech-dispatcher directory in neither emacs.conf nor in speechd.conf files,

I am willing to write a brief tutorial or put together an init.el file that could be included in hte repository. If there are some non-obvious resources, I would be glad to learn about them.

Thank you in advance for any help and ideas...

**Comment by mz-pdm** [comment]
> Examples or a working init.el file, which can be very useful for beginners,

What kind of example would you like to have? There is nothing special needed to be in the init file to start using speechd-el. As for customization, good starting points are `M-x customize-group RET speechd-el RET' and "Configuration" section of speechd-el manual. AFAIK there are no better resources. If you struggle with something particular, suggestions what could be added to the manual to make it clearer are welcome.

> Speechd-el does not honor speech-dispatcher settings set in the user configuration speech-dispatcher directory in neither emacs.conf nor in speechd.conf files,

Those configuration files are not processed by the clients but by Speech Dispatcher itself. speechd-el identifies itself to Speech Dispatcher as client "Emacs" and as the user equal to your system user name. If the matching doesn't work in your configuration files, you can ask on the Speech Dispatcher mailing list what can be wrong with your configuration.

I don't think speechd-el overrides the default parameters by default. But you can customize speechd-voices variable, see speechd-el manual. If you specify some settings for `nil' (default) voice then they should take precedence over default and configured Speech Dispatcher settings.

**Comment by mz-pdm** [comment]
Closing this as it is unclear what exactly is requested.
BTW, there are several speechd-el setup tips at https://diesenbacher.net/blog/entries/Updated-speechd-el-config.html (courtesy to Otto Diesenbacher-Reinmüller).
